//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "links")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub url: String,
    pub title: Option<String>,
    pub sensitive: bool,
    pub created_by: String,
    pub date_created: DateTimeWithTimeZone,
    pub modified_at: Option<DateTimeWithTimeZone>,
    pub archived_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::notes::Entity")]
    Notes,
    #[sea_orm(has_many = "super::grouped_links::Entity")]
    GroupedLinks,
    #[sea_orm(has_many = "super::tagged_links::Entity")]
    TaggedLinks,
}

impl Related<super::notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notes.def()
    }
}

impl Related<super::grouped_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupedLinks.def()
    }
}

impl Related<super::tagged_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaggedLinks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
