version: 2.1

executors:
  docker_latest:
    working_directory: /tmp/workspace
    docker:
      - image: docker:latest

jobs:
    build_app:
        parameters:
            with_deploy:
                type: boolean
                default: false
        executor: docker_latest
        steps:
            - run:
                name: Update the Alpine APK cache
                command: |
                    apk update
            - run:
                name: Install Git & SSH
                command: |
                    apk add git openssh-client openssh --no-cache
            - checkout
            - setup_remote_docker:
                version: 17.09.0-ce
            - restore_cache:
                keys:
                    - cargo-v0-{{ checksum "Cargo.lock" }}
            - run:
                name: Build application
                command: |
                    docker build -t $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/link-backlog:latest -t $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/link-backlog:$(git describe --tags --first-parent --abbrev=0) .
            - save_cache:
                key: cargo-v0-{{ checksum "Cargo.lock" }}
                paths:
                    - ~/.cargo
            - when:
                condition: <<parameters.with_deploy>>
                steps:
                    - run:
                        name: Publish to GitHub Container Registry
                        command: |
                            git fetch --tags
                            echo $CONTAINER_REGISTRY_PASS | docker login ghcr.io -u $CONTAINER_REGISTRY_USER --password-stdin
                            docker push $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/link-backlog:latest
                            docker push $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/link-backlog:$(git describe --tags --first-parent --abbrev=0)
                            
workflows:
    version: 2
    build:
        jobs:
            - build_app:
                name: Build & Deploy
                with_deploy: true
                filters:
                    branches:
                        only: master